### ISSUE TITLE
[Errno 3] invalid value for ai_flags.

### ISSUE THREAD

**Issue by ghost** [pascalw/Airplayer#19]
hi.
I've tried to setup Airplayer on a dreambox, using the vlc 3rdpartybackend.
when i try to start airplay, I just get:
# python airplayer.py

2011-07-04 00:25:59 [INFO] Starting Airplayer
2011-07-04 00:25:59 [DEBUG] TEMP DIR: /tmp/tmpedBiFa
Started connection to VLC
Traceback (most recent call last):
  File "airplayer.py", line 221, in <module>
    main()
  File "airplayer.py", line 217, in main
    raise e
socket.gaierror: [Errno 3] invalid value for ai_flags.

do you have any hints?
thanks in advance

**Comment by pascalw** [comment]
Seems like a permission issue with opening a port. Is port your settings.AIRPLAYER_PORT (defaults to 6002) taken or something? Do you have permissions to open that port?

**Comment by ghost** [comment]
Port is not in use. Started as Root and tried different ports
