### ISSUE TITLE
Exception upon playback?  (FIXED)

### ISSUE THREAD

**Issue by ghost** [pascalw/Airplayer#20]
Hey folks, not sure if this is the right place to put this, but ever since I upgraded my XBMC box to Natty I've been unable to play anything via Airplayer.  Trying to start a video results in "Unable to play video on xbmc-livingroom" on the iPhone, and the following string of exceptions on the terminal:

<code>
ERROR:root:Exception in I/O handler for fd 13
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/tornado/ioloop.py", line 252, in start
    self._handlers[fd](fd, events)
  File "/usr/lib/pymodules/python2.7/tornado/iostream.py", line 144, in _handle_events
    self._handle_read()
  File "/usr/lib/pymodules/python2.7/tornado/iostream.py", line 210, in _handle_read
    self._consume(loc + delimiter_len))
  File "/usr/lib/pymodules/python2.7/tornado/iostream.py", line 165, in _run_callback
    callback(_args, *_kwargs)
  File "/usr/lib/pymodules/python2.7/tornado/httpserver.py", line 292, in _on_headers
    self.stream.read_bytes(content_length, self._on_request_body)
  File "/usr/lib/pymodules/python2.7/tornado/iostream.py", line 95, in read_bytes
    callback(self._consume(num_bytes))
  File "/usr/lib/pymodules/python2.7/tornado/httpserver.py", line 314, in _on_request_body
    self.request_callback(self._request)
  File "/usr/lib/pymodules/python2.7/tornado/web.py", line 1078, in __call__
    handler = spec.handler_class(self, request, **spec.kwargs)
TypeError: **init**() got an unexpected keyword argument 'media_backend'
</code>

Any suggestions?  I'm not proficient in Python, but it looks like the Tornado web server is flaking out for some reason.  I should note that the XBMC web interfaces all appear to be working normally.

**\* EDIT ***
Found the problem; I had to recompile and reinstall Tornado.  For some reason it looks like the upgrade broke it.  I'll leave this here in case any of your other users have the problem.  Keep up the incredible work!

Thanks!

Greg Lindsey

**Comment by pascalw** [comment]
I think it could also be related to the pip requirements file not specifying a package version. Since tornado 2.0 is recently released that might have broken it. I've now added package versions to the requirements file in order to prevent backwards-incompatible changes in packages to break airplayer in the future.
